{{- if .Values.slimSharedSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-transport-secret
  namespace: {{ .Release.Namespace }}
stringData:
  SLIM_SHARED_SECRET: {{ .Values.slimSharedSecret | quote }}
{{- end }}
