apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  CORS_ALLOWED_ORIGINS: "{{ .Values.config.corsAllowedOrigins }}"
  TRANSPORT_SERVER_ENDPOINT: "{{ .Values.config.transportServerEndpoint }}"
  DEFAULT_MESSAGE_TRANSPORT: "{{ .Values.config.defaultMessageTransport }}"
  SLIM_SERVER: "{{ .Values.config.slimServer }}"
  NATS_SERVER: "{{ .Values.config.natsServer }}"
  OTLP_HTTP_ENDPOINT: "{{ .Values.config.otlpHttpEndpoint }}"
