/**
 * Map illustration buckets (generated by scripts/generate_assets.py)
 * to URLs that React `<img src>` can use.
 *
 * Vite's `import.meta.glob` with eager URL resolution gives us a
 * compile-time map of basename -> hashed URL, so a missing file
 * surfaces as `undefined` and the caller can fall back gracefully.
 */

const _byBasename = (m: Record<string, string>): Record<string, string> => {
  const out: Record<string, string> = {}
  for (const path of Object.keys(m)) {
    // path is the absolute project path; key by basename without extension
    const file = path.split("/").pop() ?? ""
    const name = file.replace(/\.(webp|png|jpg|jpeg)$/i, "")
    out[name] = m[path]
  }
  return out
}

const FRUIT_URLS: Record<string, string> = _byBasename(
  import.meta.glob("@/assets/illustrations/fruit/*.{webp,png}", {
    eager: true,
    query: "?url",
    import: "default",
  }) as Record<string, string>,
)

const ORIGIN_URLS: Record<string, string> = _byBasename(
  import.meta.glob("@/assets/illustrations/origin/*.{webp,png}", {
    eager: true,
    query: "?url",
    import: "default",
  }) as Record<string, string>,
)

const STATE_URLS: Record<string, string> = _byBasename(
  import.meta.glob("@/assets/illustrations/state/*.{webp,png}", {
    eager: true,
    query: "?url",
    import: "default",
  }) as Record<string, string>,
)

const PLAN_URLS: Record<string, string> = _byBasename(
  import.meta.glob("@/assets/illustrations/plan/*.{webp,png}", {
    eager: true,
    query: "?url",
    import: "default",
  }) as Record<string, string>,
)

export const fruitImage = (
  fruitType: string | null | undefined,
): string | null => {
  if (!fruitType) return null
  return FRUIT_URLS[fruitType.toLowerCase()] ?? null
}

export const originImage = (
  origin: string | null | undefined,
): string | null => {
  if (!origin) return null
  return ORIGIN_URLS[origin.toLowerCase()] ?? null
}

export const stateImage = (name: string): string | null => {
  return STATE_URLS[name] ?? null
}

export const planImage = (
  planType: "single_supplier" | "split_order",
): string | null => {
  return PLAN_URLS[planType] ?? null
}
