FROM node:20-alpine

WORKDIR /app

# Install wget, curl, and ping (iputils)
RUN apk add --no-cache wget curl iputils

# Copy package.json and package-lock.json, then install dependencies
COPY fruitAGNTCY/fruit_agents/fruit_cognition/frontend/package.json fruitAGNTCY/fruit_agents/fruit_cognition/frontend/package-lock.json ./

# Copy application files, including assets
COPY fruitAGNTCY/fruit_agents/fruit_cognition/frontend/ .

# This build step is simply for checking the validity of the build:
# running type checks, linting, and making sure the build is functional.
RUN ["npm", "install", "--verbose"]
RUN ["npm", "run", "build", "--verbose"]
RUN ["npm", "cache", "clean", "--force"]

# Expose port 3000
EXPOSE 3000

# Copy the script to build and serve the UI
COPY fruitAGNTCY/fruit_agents/fruit_cognition/docker/ui-build-and-serve.sh ./ui-build-and-serve.sh
# Start the application
CMD ["sh", "./ui-build-and-serve.sh"]