# SLIM v0.7+ requires to use debian trixie distribution
FROM python:3.13.11-slim-trixie

# Install system dependencies, including ping, curl, and wget
RUN apt-get update && \
    apt-get install -y --no-install-recommends git curl wget iputils-ping && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install uv and create virtual environment
RUN pip install --no-cache-dir uv && \
    uv venv -q /venv
ENV PATH="/venv/bin:$PATH"

# Set PYTHONPATH to include the application directory
ENV PYTHONPATH="/app"

WORKDIR /app
COPY fruitAGNTCY/fruit_agents/fruit_cognition/pyproject.toml fruitAGNTCY/fruit_agents/fruit_cognition/uv.lock ./
RUN uv sync --locked --no-editable

COPY fruitAGNTCY/fruit_agents/fruit_cognition/ .
CMD ["uv", "run", "python", "agents/farms/brazil/farm_server.py"]