{{- if and .Values.config.slimSharedSecret (not .Values.externalSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-transport-secret
  namespace: {{ .Release.Namespace }}
stringData:
  SLIM_SHARED_SECRET: {{ .Values.config.slimSharedSecret | quote }}
{{- end }}
